### ISSUE TITLE
Use Select2 for Pages Dropdown

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/Behavior-Flow#1]
The page dropdown is easy to use with just a couple of pages, but it will become unusable with many pages.

**Comment by siamkreative** [comment]
- Main script depends on Select2 script - 196c6fe5bd305bb04ddf0a877a946d1cc2ae7c85
- Add assets - 744003e6505469ee5f5accaee5c168e737c5ef6f
- Switch to version 4.0.0 of Select2 - 59d63bd95933d4070ee8f2459eb286c5083c4e74
